class: "{{cookiecutter.}}.utils.processing.End2EndProcessor"
# when using jit models use:
# model
#   # path to the jit file, can be relative to the checkpoints folder
#   jit_path: "/path/to/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/checkoints/jit_model.ptc"
#   device: "cuda" # device where the model is put on, optional

# otherwise use
model:
  # name of the class of the torch.nn module, must be importable from models module
  class: "{{cookiecutter.model_name}}" 
  # path to the state dict of the module, can be relative to the checkpoints folder
  state_dict_path: "/path/to/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/checkoints/default_state_dict.pt"
  # device where the model is put on, optional
  device: "cuda" 
  # parameters which are passed to the init method of the class
  # - model_param_1: 5 
  # - model_param_2: 15

preprocessor:
  # name of the class of the preprocessor, must be importable from preprocessor module
  class: "{{cookiecutter.dataset_name}}Preprocessor"
  # define the submpdules and their arguments, nesting is possible, classes must be importable from the preprocessing module
  submodule_1: 
    class: "ExampleSubmodule" 
    # submodule_param_1: 1
    # submodule_param_2: 2
  submodule_2: 
    class: "ExampleSubmodule"
    # submodule_param_1: 3
    # submodule_param_2: 4

postprocessor:
  # name of the class of the postprocessor, must be importable from postprocessor module
  class: "{{cookiecutter.dataset_name}}Preprocessor"
  # define the submpdules and their arguments, nesting is possible, classes must be importable from the postprocessing module
  submodule_1: 
    class: "ExampleSubmodule" 
    # submodule_param_1: 1
    # submodule_param_2: 2
  submodule_2: 
    class: "ExampleSubmodule"
    # submodule_param_1: 3
    # submodule_param_2: 4